### PR TITLE
Begin draft tutorial text on transformers

### PR DESCRIPTION
**Pull request by david-a-wheeler**

### CODE REVIEW

**Comment by david-a-wheeler** [comment]
This isn't complete, this is more of a placeholder.

**Review by expln — APPROVED** [review]
Looks nice!

**Comment by david-a-wheeler** [comment]
No comment on my transformers puns? :-)

Thanks!

**Comment by david-a-wheeler** [comment]
You found it! It's an old kids' show, but they released yet another movie this year (2023) in the franchise.

**Comment by expln** [comment]
Good to know! I even found that movie https://www.imdb.com/title/tt5090568/ :)

**Pull request merged**
